name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360  # Max limit for free GitHub Actions

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Set Fixed RDP Password
        run: |
          $Password = ConvertTo-SecureString "MohsinXX" -AsPlainText -Force
          Set-LocalUser -Name "Administrator" -Password $Password
        shell: pwsh

      - name: Enable RDP & Firewall Rules
        run: |
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          netsh advfirewall firewall set rule group="Remote Desktop" new enable=Yes
          net stop termservice /y
          net start termservice
        shell: cmd

      - name: Prevent Auto Shutdown (Keep Alive)
        run: |
          powercfg -change -standby-timeout-ac 0
          powercfg -change -monitor-timeout-ac 0
          powercfg -change -disk-timeout-ac 0
        shell: cmd

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py

      - name: Keep Alive Script (Prevent Timeout)
        run: |
          while ($true) { Start-Sleep -Seconds 600 }
        shell: pwsh
